# Artificial Neural Network

### Importing the libraries

In [45]:
#first step is to download tensorflow
import sys
!{sys.executable} -m pip install tensorflow
import numpy as np
import pandas as pd
import tensorflow as tf

In [46]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [47]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [48]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [49]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [50]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#we want to transform x values in all rows but only colum 2 (gender)
X[:, 2] = le.fit_transform(X[:, 2])

In [51]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [52]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#must change the index of the feature for transformation, column 1
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [53]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Feature Scaling

In [54]:
#feature scaling a must for all variables in deep learning (neural networds)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [55]:
print(X_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [56]:
print(X_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


### Splitting the dataset into the Training set and Test set

In [57]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [58]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [59]:
#no unified set of neurons to choose (units) so you have to experiment...
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [60]:
#to add a 2nd layer just copy and paste, no modification needed unless you want to change units...
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [61]:
#for output layer you need to have dimenions of output (binary variable here) to a one.  If non binary it must change
#change activation function to signmoid to get prob of churn for customers
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Training the ANN

### Compiling the ANN

In [62]:
#adam optimizer utilizes stochastic gradient descent, best option
#binary_crossentropy is values needed for loss using binary outcomes, non binary is categorical_crossentropy
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [63]:
#artifical neural networks need x and y, but two additional peraimters
#batch size groups data default value is 32
#epocs = how many cycles the neural network runs through. default is around 100, can not be too small...
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 580us/step - loss: 0.5950 - accuracy: 0.7649
Epoch 2/100
250/250 [==============================] - 0s 550us/step - loss: 0.4931 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 550us/step - loss: 0.4559 - accuracy: 0.7971
Epoch 4/100
250/250 [==============================] - 0s 534us/step - loss: 0.4282 - accuracy: 0.8121
Epoch 5/100
250/250 [==============================] - 0s 522us/step - loss: 0.4092 - accuracy: 0.8285
Epoch 6/100
250/250 [==============================] - 0s 535us/step - loss: 0.3934 - accuracy: 0.8357
Epoch 7/100
250/250 [==============================] - 0s 522us/step - loss: 0.3804 - accuracy: 0.8432
Epoch 8/100
250/250 [==============================] - 0s 527us/step - loss: 0.3704 - accuracy: 0.8494
Epoch 9/100
250/250 [==============================] - 0s 540us/step - loss: 0.3629 - accuracy: 0.8512
Epoch 10/100
250/250 [==============================] - 0s 536us/step - l

250/250 [==============================] - 0s 515us/step - loss: 0.3334 - accuracy: 0.8629
Epoch 80/100
250/250 [==============================] - 0s 511us/step - loss: 0.3333 - accuracy: 0.8619
Epoch 81/100
250/250 [==============================] - 0s 508us/step - loss: 0.3331 - accuracy: 0.8606
Epoch 82/100
250/250 [==============================] - 0s 515us/step - loss: 0.3330 - accuracy: 0.8626
Epoch 83/100
250/250 [==============================] - 0s 564us/step - loss: 0.3331 - accuracy: 0.8630
Epoch 84/100
250/250 [==============================] - 0s 505us/step - loss: 0.3332 - accuracy: 0.8625
Epoch 85/100
250/250 [==============================] - 0s 508us/step - loss: 0.3330 - accuracy: 0.8645
Epoch 86/100
250/250 [==============================] - 0s 523us/step - loss: 0.3329 - accuracy: 0.8618
Epoch 87/100
250/250 [==============================] - 0s 539us/step - loss: 0.3330 - accuracy: 0.8629
Epoch 88/100
250/250 [==============================] - 0s 538us/step - loss:

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [64]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [66]:
#must call accuracy score if you want to see it..
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1512   83]
 [ 197  208]]


0.86